Update buildspec-terraform-plan.yml

diff --git a/buildspec-terraform-plan.yml b/buildspec-terraform-plan.yml
--- a/buildspec-terraform-plan.yml
+++ b/buildspec-terraform-plan.yml
@@ -10,22 +10,25 @@ phases:
       - unzip terraform_1.11.2_linux_amd64.zip
       - sudo mv terraform /usr/local/bin/
       - terraform --version
+
   pre_build:
     commands:
       - echo "Initializing Terraform..."
       - terraform init -backend-config="bucket=${STATE_FILE_BUCKET}" -backend-config="key=${STATE_FILE_PATH}" -backend-config="region=${REGION}" -backend-config="encrypt=true" -backend-config="dynamodb_table=${DB_TABLE}"
+
   build:
     commands:
       - echo "Planning Terraform deployment..."
       - terraform plan --var-file="${TF_VAR}" > plan_output.txt 2>&1 || echo "Terraform plan failed" > plan_failed.txt
-      - if [ -f plan_failed.txt ]; then
-          echo "Terraform plan failed! Sending notification...";
-          ERROR_MSG=$(tail -n 20 plan_output.txt | sed 's/"/\x27/g');  # Escape quotes to avoid SES errors
+      - |
+        if [ -f plan_failed.txt ]; then
+          echo "Terraform plan failed! Sending notification..."
+          ERROR_MSG=$(tail -n 20 plan_output.txt | sed 's/"/\x27/g')  # Escape quotes to avoid SES errors
           aws ses send-email \
             --from "no-reply@firminiq.com" \
-            --destination "ToAddresses=ngfirminiq@gmail.com" \
-            --message "Subject={Data=Terraform Plan Failed},Body={Text={Data=Terraform plan failed in AWS CodeBuild. Error Details:\n\n$ERROR_MSG}}";
-          exit 1;
+            --destination ToAddresses="ngfirminiq@gmail.com" \
+            --message "Subject={Data=Terraform Plan Failed},Body={Text={Data=Terraform plan failed in AWS CodeBuild. Error Details:\n\n$ERROR_MSG}}"  
+          exit 1
         fi
 
 
